### ISSUE TITLE
Missing libs with lua 5.3 and windows x64

### ISSUE THREAD

**Issue by LennyPenny** [moteus/lua-lluv#13]
Hey I couldn't install this from luarocks because I got some linker errors. 

>Error	8	error LNK2001: unresolved external symbol GetAdaptersAddresses	C:\Users\Lenny\Documents\GitHub\lua-lluv\msvc\libuv.lib(util.obj)	lluv
Error	7	error LNK2001: unresolved external symbol GetProcessMemoryInfo	C:\Users\Lenny\Documents\GitHub\lua-lluv\msvc\libuv.lib(util.obj)	lluv

I cloned it and changed the linker config to this: 
![linker config](http://i.imgur.com/MJPvJ7O.png)

I'm using the latest master from the libuv repo build in x64 and lua 5.3 x64. 
I had to add Iphlpapi.lib and Psapi.lib to the linker and ignore the LIBCMT default lib. 

Is that fixable?

**Comment by moteus** [comment]
I think you use static link with libuv. In this case you should build lluv and libuv with same runtime.
Ignoring LIBCMT is not good choice.
Also you can change `libraries = {"libuv", "ws2_32"}` in rockspec to `libraries = {"libuv", "ws2_32", "Iphlpapi", "Psapi"}` and try install this.

I try test static link tomorrow and update rockspecs.

**Comment by LennyPenny** [comment]
Thanks, yeah I'm using a static libuv lib

**Comment by moteus** [comment]
Could you test luarocks install now?

**Comment by LennyPenny** [comment]
Still getting the errors which made me disable LIBCMT but it's a step 
![errors](http://i.imgur.com/rnUJ4nQ.png)

**Comment by moteus** [comment]
Try build libuv with same runtime as Lua.
lua.exe/lua.dll/lluv.dll should use same MSVC runtime library.
If you link Lua module with static lib this static lib also should use same runtime.
(Project options->C/C++->Code Generation->Runtime Library)

**Comment by LennyPenny** [comment]
Woa awesome, thanks! 
It's a bit weird to build a static lib with `Multi-threaded DLL (/MD)` but it did the job.
